### ISSUE TITLE
Release crate to Cargo

### ISSUE THREAD

**Issue by Sollimann** [benmkw/imnodes-rs#3]
Hey, I would really like to use your crate in one of my projects. Could you release it to Cargo? :)

**Comment by Sollimann** [comment]
should be fine publishing even though you rely on a C library https://kornel.ski/rust-sys-crate

**Comment by benmkw** [comment]
does using a git dependency work for you as well? https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

you would need to add the following to your Cargo.toml 
```toml
imnodes = { git = "https://github.com/benmkw/imnodes-rs", rev = "<some git hash>" } 
```

**Comment by benmkw** [comment]
just published it 

https://crates.io/crates/imnodes-sys
and
https://crates.io/crates/imnodes
